'use strict';
const $=s=>document.querySelector(s),KEY='math-chain-v1';
const fresh=()=>({coins:300,completed:[],best:0,sound:true});
let data=fresh(),storageOK=true;
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw&&typeof raw==='object'){data.coins=Number.isSafeInteger(raw.coins)&&raw.coins>=0?raw.coins:300;data.completed=Array.isArray(raw.completed)?[...new Set(raw.completed.filter(n=>Number.isInteger(n)&&n>=0&&n<15))]:[];data.best=Number.isSafeInteger(raw.best)&&raw.best>=0?raw.best:0;data.sound=raw.sound!==false;}}catch(e){storageOK=false}
let run=null,ticker=null,ctx;
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(data))}catch(e){storageOK=false}header()};
function header(){$('#coins').textContent=data.coins;$('#sound').textContent='Sound: '+(data.sound?'on':'off')}
function beep(ok=true){if(!data.sound)return;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=ok?660:180;g.gain.setValueAtTime(.06,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.15);o.start();o.stop(ctx.currentTime+.15)}catch(e){}}
function stop(){clearInterval(ticker);ticker=null}
function render(html){$('#app').innerHTML=html;header()}
function home(){stop();run=null;render(`<section class="hero"><div><div class="eyebrow">YOUR DAILY BRAIN WORKOUT</div><h1>Small numbers.<br><em>Big brain energy.</em></h1><p>A chain of arithmetic challenges. Just you, your mind, and the next answer. How far can you go without a calculator?</p><div class="actions"><button id="play">Let's play →</button><button class="secondary" id="help">How to play</button></div>${!storageOK?'<p class="notice">Saving is unavailable in this browser. Progress lasts for this session.</p>':''}</div><div class="preview" aria-hidden="true"><span class="tag">MENTAL MATH • LEVEL 04</span><div class="formula">6 × 4 + 8 = ?</div><div class="answer">32 <span style="float:right">✓</span></div><p>One answer closer to your next level.</p></div></section><section class="stats"><div class="stat"><b>${data.completed.length}/15</b><span>Levels completed</span></div><div class="stat"><b>${data.best}</b><span>Best round score</span></div><div class="stat"><b>100%</b><span>Calculator-free fun</span></div></section><div class="actions"><button class="small" id="reset">Reset progress</button></div>`);$('#play').onclick=levels;$('#help').onclick=help;$('#reset').onclick=()=>{if(confirm('Delete all saved progress, coins and best score?')){data=fresh();save();home()}}}
function help(){render(`<section class="help"><div class="eyebrow">THE RULES</div><h2>A little focus goes a long way.</h2><ul><li>Complete 10 questions to clear a level. Each correct answer earns 10 points.</li><li>Parentheses first, then multiplication and division, then addition and subtraction. Operations of equal priority go from left to right.</li><li>Classic mode has no deadline. Sprint mode gives you 2 minutes for the whole round, plus 2 points per whole second remaining when completed.</li><li>Wrong answers cost no lives. Try again. Use up to 3 free hints each round; extra hints cost 25 coins each.</li><li>Completing a level earns 50 coins and unlocks the next level. You can replay completed levels.</li><li>Progress saves automatically when browser storage is available. Reset progress on the home screen starts a new game.</li><li>The timer keeps running if you switch tabs. All answers are whole numbers; some may be negative.</li></ul><button id="back">Back to home</button></section>`);$('#back').onclick=home}
function levels(){stop();run=null;render(`<div class="toolbar"><div><div class="eyebrow">CHOOSE YOUR CHALLENGE</div><h2>Your mental math journey</h2></div><button id="back" class="small">← Home</button></div><p>Clear each level to unlock the next. Ten questions. A fresh set every time.</p><label for="mode">Game mode </label><select id="mode"><option value="classic">Classic · no time limit</option><option value="sprint">Sprint · 2 minutes</option></select><div class="levels">${Array.from({length:15},(_,i)=>{const done=data.completed.includes(i),locked=i>0&&!data.completed.includes(i-1);return `<button data-level="${i}" class="level ${done?'done':''}" ${locked?'disabled':''}><span>${locked?'LOCKED':done?'COMPLETED ✓':'READY TO PLAY'}</span><b>${String(i+1).padStart(2,'0')}</b><span>${i<3?'Add & subtract':i<6?'Multiply & divide':i<10?'Order matters':'Mixed mastery'}</span></button>`}).join('')}</div>`);$('#back').onclick=home;document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(Number(b.dataset.level),$('#mode').value))}
function start(level,mode){stop();run={level,mode,index:0,score:0,hints:3,start:Date.now(),mistakes:0,review:[],ended:false,questions:[]};let seen=new Set;while(run.questions.length<10){const q=MathEngine.generate(level);if(!seen.has(q.text)){seen.add(q.text);run.questions.push(q)}}game();ticker=setInterval(tick,200)}
function elapsed(){return Math.floor((Date.now()-run.start)/1000)}
function left(){return Math.max(0,120-elapsed())}
function fmt(t){return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}
function tick(){if(!run||run.ended)return;if(run.mode==='sprint'&&left()===0){finish(false);return}const t=$('#timer');if(t){t.textContent=fmt(run.mode==='sprint'?left():elapsed());t.classList.toggle('red',run.mode==='sprint'&&left()<30)}}
function game(){const q=run.questions[run.index];render(`<section class="game"><div class="toolbar"><button class="small" id="quit">← Levels</button><span class="eyebrow">LEVEL ${run.level+1} · ${run.mode.toUpperCase()}</span></div><div class="pills"><span class="pill">Question <b>${run.index+1}/10</b></span><span class="pill">Score <b>${run.score}</b></span><span class="pill">⏱ <b id="timer">${fmt(run.mode==='sprint'?left():elapsed())}</b></span></div><div class="progress" aria-label="Round progress"><i style="width:${run.index*10}%"></i></div><div class="card question"><div class="eyebrow">SOLVE IT IN YOUR HEAD</div><div class="formula">${q.text} = ?</div><form id="form"><input id="answer" type="text" inputmode="text" autocomplete="off" aria-label="Your answer" placeholder="Your answer"><button type="submit">Check →</button></form><div class="feedback" id="feedback" role="status" aria-live="polite"></div><div class="keypad" aria-label="Number keypad">${['1','2','3','4','5','6','7','8','9','−','0','⌫'].map(k=>`<button type="button" data-key="${k}" aria-label="${k==='⌫'?'Backspace':k==='−'?'Minus':k}">${k}</button>`).join('')}</div><button class="secondary" id="hint">✦ ${run.hints>0?'Hint · '+run.hints+' free left':'Hint · 25 coins'}</button></div></section>`);$('#quit').onclick=()=>{if(confirm('Leave this round? Current round progress will be lost.'))levels()};$('#form').onsubmit=e=>{e.preventDefault();check()};$('#hint').onclick=hint;document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const input=$('#answer'),k=b.dataset.key;input.value=k==='⌫'?input.value.slice(0,-1):k==='−'?(input.value.startsWith('-')?input.value.slice(1):'-'+input.value):input.value.length<9?input.value+k:input.value;input.focus()});$('#answer').focus();tick()}
function check(){if(!run||run.ended)return;if(run.mode==='sprint'&&left()===0){finish(false);return}const val=$('#answer').value.trim();if(!/^-?\d{1,8}$/.test(val)){$('#feedback').textContent='Enter a whole number, using − for a negative answer.';return}const q=run.questions[run.index];if(Number(val)!==q.answer){run.mistakes++;beep(false);$('#feedback').textContent='Not quite — take another look and try again.';$('#answer').select();return}beep();run.score+=10;run.review.push(q);run.index++;if(run.index===10)finish(true);else game()}
function hint(){if(run.mode==='sprint'&&left()===0){finish(false);return}if(run.hints>0)run.hints--;else if(data.coins>=25){data.coins-=25;save()}else{$('#feedback').textContent='You need 25 coins for another hint.';return}$('#feedback').textContent=run.questions[run.index].hint;$('#feedback').classList.add('hint');$('#hint').textContent='✦ '+(run.hints>0?'Hint · '+run.hints+' free left':'Hint · 25 coins')}
function finish(won){if(run.ended)return;run.ended=true;stop();const seconds=elapsed(),bonus=won&&run.mode==='sprint'?left()*2:0;run.score+=bonus;if(won){data.coins+=50;if(!data.completed.includes(run.level))data.completed.push(run.level)}data.best=Math.max(data.best,run.score);save();beep(won);render(`<section class="result"><div class="eyebrow">${won?'CHALLENGE COMPLETE':'TIME’S UP'}</div><h1>${won?'Nicely <em>done.</em>':'Keep <em>practicing.</em>'}</h1><p>${won?'Your next challenge is waiting.':'Every question is a chance to improve. Try another round.'}</p><div class="stats"><div class="stat"><b>${run.score}</b><span>Score · ${bonus} time bonus</span></div><div class="stat"><b>${won?'+50':'+0'}</b><span>Coins earned</span></div><div class="stat"><b>${fmt(seconds)}</b><span>Time · ${run.mistakes} mistakes</span></div></div><p>${run.index}/10 questions solved</p><div class="actions"><button id="again">Play again</button>${won&&run.level<14?'<button class="secondary" id="next">Next level →</button>':''}<button class="secondary" id="levels">All levels</button><button class="small" id="home">Home</button></div><div class="card review"><h3>Round answers</h3>${run.questions.slice(0,won?10:run.index+1).map((q,i)=>`<p>${i<run.index?'✓':'○'} ${q.text} = <strong>${q.answer}</strong></p>`).join('')}</div></section>`);const {level,mode}=run;$('#again').onclick=()=>start(level,mode);if($('#next'))$('#next').onclick=()=>start(level+1,mode);$('#levels').onclick=levels;$('#home').onclick=home}
$('#sound').onclick=()=>{data.sound=!data.sound;save();if(data.sound)beep()};header();home();
